#!/bin/bash

XPROV_JAR=target/xprova-0.0.1-SNAPSHOT-jar-with-dependencies.jar
MVNOUT=mvn_output.txt
args=$@

if [[ $1 = "--rebuild" || $1 = "-r" ]]
then
	type mvn >/dev/null 2>&1 || { echo >&2 "maven is not installed"; exit 1; }
	echo "Cleaning existing build ..."
	mvn clean &> /dev/null
	args=${@:2}
elif [[ $1 = "--clean" || $1 = "-c" ]]
then
	type mvn >/dev/null 2>&1 || { echo >&2 "maven is not installed"; exit 1; }
	echo "Cleaning existing build (including maven dependencies) ..."
	mvn clean -U &> /dev/null
	args=${@:2}
fi

if [ ! -f $XPROV_JAR ]
then

	type mvn >/dev/null 2>&1 || { echo >&2 "maven is not installed"; exit 1; }

	echo "Building Xprova for first time use ..."

	mvn package > $MVNOUT

	if [ $? -ne 0 ]; then
		echo "Maven build failed!"
		cat $MVNOUT
		echo "See output in file '$MVNOUT' for more informations"
		exit 1
	fi
	rm $MVNOUT

fi

if [ `uname -o` == "Cygwin" ]
then
	stty -icanon min 1 -echo
	java -jar -Djline.terminal=jline.UnixTerminal $XPROV_JAR "$args"
	stty icanon echo
else
	java -jar $XPROV_JAR "$args"
fi

