/* Generated by Yosys 0.6 (git sha1 5869d26, i686-pc-mingw32-gcc 4.8.1 -Os) */

(* top =  1  *)
(* src = "graycounter.v:1" *)
module graycounter(clk, rst, ena, count);
  (* src = "graycounter.v:9" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  (* src = "graycounter.v:3" *)
  input clk;
  (* src = "graycounter.v:5" *)
  output [1:0] count;
  (* src = "graycounter.v:3" *)
  input ena;
  (* src = "graycounter.v:3" *)
  input rst;
  NOT _07_ (
    .a(ena),
    .y(_03_)
  );
  AND _08_ (
    .a(_03_),
    .b(count[0]),
    .y(_04_)
  );
  NOT _09_ (
    .a(count[1]),
    .y(_05_)
  );
  AND _10_ (
    .a(ena),
    .b(_05_),
    .y(_06_)
  );
  OR _11_ (
    .a(_06_),
    .b(_04_),
    .y(_00_[0])
  );
  AND _12_ (
    .a(_03_),
    .b(count[1]),
    .y(_01_)
  );
  AND _13_ (
    .a(ena),
    .b(count[0]),
    .y(_02_)
  );
  OR _14_ (
    .a(_02_),
    .b(_01_),
    .y(_00_[1])
  );
  DFF _15_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RS(rst)
  );
  DFF _16_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RS(rst)
  );
endmodule
