/* Generated by Yosys 0.6 (git sha1 5869d26, i686-pc-mingw32-gcc 4.8.1 -Os) */

(* top =  1  *)
(* src = "graycounter2.v:1" *)
module graycounter2(clk, rst, ena1, ena2, count);
  (* src = "graycounter2.v:9" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  (* src = "graycounter2.v:3" *)
  input clk;
  (* src = "graycounter2.v:5" *)
  output [1:0] count;
  (* src = "graycounter2.v:3" *)
  input ena1;
  (* src = "graycounter2.v:3" *)
  input ena2;
  (* src = "graycounter2.v:3" *)
  input rst;
  NOT _14_ (
    .a(ena2),
    .y(_11_)
  );
  OR _15_ (
    .a(_11_),
    .b(ena1),
    .y(_12_)
  );
  NOT _16_ (
    .a(ena1),
    .y(_13_)
  );
  OR _17_ (
    .a(ena2),
    .b(_13_),
    .y(_01_)
  );
  AND _18_ (
    .a(_01_),
    .b(_12_),
    .y(_02_)
  );
  AND _19_ (
    .a(_02_),
    .b(count[0]),
    .y(_03_)
  );
  NOT _20_ (
    .a(count[1]),
    .y(_04_)
  );
  AND _21_ (
    .a(ena2),
    .b(_13_),
    .y(_05_)
  );
  AND _22_ (
    .a(_11_),
    .b(ena1),
    .y(_06_)
  );
  OR _23_ (
    .a(_06_),
    .b(_05_),
    .y(_07_)
  );
  AND _24_ (
    .a(_07_),
    .b(_04_),
    .y(_08_)
  );
  OR _25_ (
    .a(_08_),
    .b(_03_),
    .y(_00_[0])
  );
  AND _26_ (
    .a(_02_),
    .b(count[1]),
    .y(_09_)
  );
  AND _27_ (
    .a(_07_),
    .b(count[0]),
    .y(_10_)
  );
  OR _28_ (
    .a(_10_),
    .b(_09_),
    .y(_00_[1])
  );
  DFF _29_ (
    .CK(clk),
    .D(_00_[0]),
    .Q(count[0]),
    .RS(rst)
  );
  DFF _30_ (
    .CK(clk),
    .D(_00_[1]),
    .Q(count[1]),
    .RS(rst)
  );
endmodule
